"""
Org-structure section — a seat-level map of who holds which job at each team,
sitting directly under the staff-moves board it shares a subject with.

Data comes in two layers.

  data/org_structure.csv is GENERATED by scripts/parse_org_structure.py from a
  community-maintained document (data/org_structure_raw.txt) compiled from public
  LinkedIn profiles and posted to the f1technical "Moving F1-Staff" thread on
  2026-08-05. Never hand-edit it; a re-parse overwrites it.

  data/org_overrides.csv is the curated layer on top, and is where our own
  verification lives — one row per confirm / correct / add / remove, each carrying
  the source URL and a source_type. That separation is the point: the document has
  real errors (a team principal's title on the wrong person, four misspelt race
  engineers) and we need those fixes to survive the next re-parse.

Every seat therefore carries a source_type: community-doc (unverified), press,
official (F1/FIA), or first-party (the team's own announcement). It drives the
"Verified" column, the pale tile border in the org chart, and one of the KPIs —
so the unverified bulk is never presented as though it were checked.

WHAT THIS IS NOT: a headcount census. The document names 7.8% (Alpine) to 20.5%
(Audi) of each team's real staff, and covers Production at ~7% of entries where a
real F1 team runs nearer 30% — engineers keep public LinkedIn profiles, machinists
and technicians largely do not. So the raw seat counts measure how visible and how
thoroughly covered a team is, NOT how big it is. Every count here is labelled
"seats mapped" for that reason, and the real-headcount bar in the Team Size card
above remains the only honest size comparison.

What it IS good for, and why it earns a place next to staff_moves.csv:
  - looking up who currently holds a named seat, with the department around them;
  - joining our tracked moves to a destination *seat*, so "X went to Williams"
    becomes "X went to Williams as Head of Model Design, in Aerodynamics";
  - the churn view — of the seats we can see in a department, what share are
    people who arrived recently. That is a ratio inside one biased sample, so
    the coverage bias largely divides out, unlike the raw counts.
"""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from dash import (html, dcc, dash_table, callback, ctx, no_update,
                  Input, Output, State)
import dash_bootstrap_components as dbc

from f1lib.components import kpi, card, theme, GFX
from f1lib.config import TEAM_COLORS, CARD_BG, ACCENT, TEXT_MAIN, TEXT_DIM, GRID_CLR
from f1lib.names import norm as norm_key, same_person, surname_key
from tabs.hr import moves_df

_ORG_PATH = Path("data/org_structure.csv")
_ORG_COLS = ["team", "department", "subunit", "role", "name", "name_key",
             "seniority", "confidence", "note"]

# Hand-curated corrections layered on top. org_structure.csv is GENERATED from the
# document and gets overwritten on every re-parse, so anything we verify ourselves
# has to live outside it — hence this overlay rather than editing rows in place.
_OVR_PATH = Path("data/org_overrides.csv")
_OVR_COLS = ["action", "team", "match_name", "department", "subunit", "role",
             "name", "seniority", "source", "source_type", "checked", "note"]

# How a seat came to be believed. Ordered weakest -> strongest.
_VERIFY_ORDER = ["community-doc", "press", "official", "first-party"]
_VERIFY_LABEL = {
    "community-doc": "Community document only",
    "press": "Press-confirmed",
    "official": "Confirmed by F1/FIA",
    "first-party": "Confirmed by the team itself",
}

# Fixed department order — structure first, then the support functions, so the
# icicle and the churn grid read the same way on every team.
_DEPT_ORDER = [
    "Executive", "Board", "C-Suite", "Design", "Aerodynamics",
    "Vehicle Performance", "Power Unit", "R&D", "Electronics", "Software & IT",
    "Race Team", "Operations", "Engineering (US)", "Non-Racing", "Heritage",
]

# Dark categorical palette, same family as the HR donut (validated against the
# #1A1A2E card surface). Department tiles carry a direct text label as the
# secondary encoding, so CVD separability is not load-bearing.
_DEPT_PALETTE = ["#3987e5", "#199e70", "#c98500", "#008300", "#9085e9",
                 "#e66767", "#d55181", "#d95926", "#4b9fd5", "#7d8a99"]

_SENIORITY_BANDS = {
    1: "Owner / CEO / TP",
    2: "C-suite / Exec director",
    3: "Director / Chief",
    4: "Head / Manager",
    5: "Principal / Lead",
    6: "Senior",
    7: "Other / unspecified",
}

_INCUMBENT_CLR = "#3d4a5c"   # muted: seat we have no move on record for
_ARRIVAL_CLR = ACCENT        # seat filled by someone in staff_moves.csv
# Border, not fill: verification is a separate question from arrival, so it needs
# its own channel rather than competing for the same one.
_VERIFY_CLR = "#f0f0f0"


# ── Loader (mtime-cached, mirrors the staff-moves loader) ─────
def _load_org() -> pd.DataFrame:
    if _ORG_PATH.exists():
        try:
            df = pd.read_csv(_ORG_PATH, encoding="utf-8")
            for c in _ORG_COLS:
                if c not in df.columns:
                    df[c] = pd.NA
            df["seniority"] = pd.to_numeric(df["seniority"], errors="coerce").fillna(7).astype(int)
            for c in ("team", "department", "subunit", "role", "name", "confidence", "note"):
                df[c] = df[c].fillna("").astype(str).str.strip()
            # Vacant seats are useful context but cannot be joined or named.
            return df[_ORG_COLS]
        except Exception as _exc:
            print(f"Org structure           : failed to read ({_exc})")
    return pd.DataFrame(columns=_ORG_COLS)


def _load_overrides() -> pd.DataFrame:
    if _OVR_PATH.exists():
        try:
            df = pd.read_csv(_OVR_PATH, encoding="utf-8")
            for c in _OVR_COLS:
                if c not in df.columns:
                    df[c] = ""
            # Everything is read as text, seniority included — a blank cell means
            # "leave the parsed value alone", which an int column cannot express.
            for c in _OVR_COLS:
                df[c] = (df[c].fillna("").astype(str).str.strip()
                         .replace({"nan": "", "<NA>": ""}))
            return df[_OVR_COLS]
        except Exception as _exc:
            print(f"Org overrides           : failed to read ({_exc})")
    return pd.DataFrame(columns=_OVR_COLS)


def _as_band(value, default: int = 7) -> int:
    """Seniority from an override cell. Read as text, so it can arrive as '1', '1.0'
    or blank depending on how pandas typed the column."""
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def _apply_overrides(org: pd.DataFrame, ovr: pd.DataFrame) -> pd.DataFrame:
    """Layer curated confirmations/corrections/additions over the parsed document.

    A `confirm` records who verified the seat and leaves it otherwise untouched;
    `correct` rewrites the name and/or role (the document has real errors — a
    misspelt race engineer, a team principal's title on the wrong person);
    `add` appends a seat the document missed; `remove` drops one.
    """
    org = org.copy()
    org["source"] = "the community org-structure document"
    org["source_type"] = "community-doc"
    org["checked"] = ""
    org["verify_note"] = ""
    if ovr.empty:
        return org

    def target(team: str, match: str, dept: str) -> pd.Index:
        """Rows an override applies to.

        `department` narrows the match rather than setting a value, because a name
        can legitimately appear twice under one team — Mattia Binotto sits on Audi's
        board AND in its executive team, and only the executive entry carries the
        job title we are correcting.
        """
        cand = org.index[org["team"] == team]
        if dept:
            cand = pd.Index([i for i in cand if org.at[i, "department"] == dept])
        return pd.Index([i for i in cand if same_person(org.at[i, "name"], match)])

    additions = []
    drop: list[int] = []
    for _, o in ovr.iterrows():
        act = o["action"].lower()
        if act == "add":
            additions.append(dict(
                team=o["team"], department=o["department"], subunit=o["subunit"],
                role=o["role"], name=o["name"], name_key=norm_key(o["name"]),
                seniority=_as_band(o["seniority"]),
                confidence="stated", note="", source=o["source"],
                source_type=o["source_type"], checked=o["checked"],
                verify_note=o["note"]))
            continue
        idx = target(o["team"], o["match_name"], o["department"])
        if not len(idx):
            print(f"Org overrides           : no match for {o['match_name']} @ {o['team']}")
            continue
        if act == "remove":
            drop.extend(idx)
            continue
        for i in idx:
            if act == "correct":
                if o["name"]:
                    org.at[i, "name"] = o["name"]
                    org.at[i, "name_key"] = norm_key(o["name"])
                if o["role"]:
                    org.at[i, "role"] = o["role"]
                if str(o["seniority"]).strip():
                    org.at[i, "seniority"] = _as_band(o["seniority"])
            org.at[i, "source"] = o["source"]
            org.at[i, "source_type"] = o["source_type"]
            org.at[i, "checked"] = o["checked"]
            org.at[i, "verify_note"] = o["note"]

    if drop:
        org = org.drop(index=drop)
    if additions:
        org = pd.concat([org, pd.DataFrame(additions)], ignore_index=True)
    return org


_ORG_CACHE: dict = {"mtime": None, "df": pd.DataFrame(columns=_ORG_COLS)}


def org_df() -> pd.DataFrame:
    """Org structure with overrides applied, re-read when either CSV changes."""
    def _mtime(p: Path):
        try:
            return p.stat().st_mtime if p.exists() else None
        except OSError:
            return None
    key = (_mtime(_ORG_PATH), _mtime(_OVR_PATH))
    if key != _ORG_CACHE["mtime"]:
        _ORG_CACHE["df"] = _apply_overrides(_load_org(), _load_overrides())
        _ORG_CACHE["mtime"] = key
    return _ORG_CACHE["df"]


# ── Join: which mapped seats are people we track a move for ───
def _annotate_moves(org: pd.DataFrame, moves: pd.DataFrame) -> pd.DataFrame:
    """Tag each named seat with the move that put the person in it, if we have one.

    Matching is bucketed by surname so this stays O(n) rather than comparing every
    seat against every move.
    """
    org = org.copy()
    org["arrived_from"] = ""
    org["arrived_season"] = pd.NA
    org["arrived_status"] = ""
    if moves.empty or org.empty:
        return org

    bucket: dict[str, list] = defaultdict(list)
    for _, m in moves.iterrows():
        bucket[surname_key(m["name"])].append(m)

    for idx, row in org.iterrows():
        if not row["name"]:
            continue
        for m in bucket.get(surname_key(row["name"]), []):
            # The move must land at the team whose chart this seat is on.
            if m["to_team"] == row["team"] and same_person(row["name"], m["name"]):
                org.at[idx, "arrived_from"] = m["from_team"]
                org.at[idx, "arrived_season"] = m["season"]
                org.at[idx, "arrived_status"] = m["status"]
                break
    return org


def org_annotated() -> pd.DataFrame:
    """Org structure joined to the staff-moves board."""
    return _annotate_moves(org_df(), moves_df())


def _rgba_mix(hex_color: str, toward: str = CARD_BG, amount: float = 0.45) -> str:
    """Darken a department colour toward the card surface, so a sub-unit tile reads
    as a shade of its department rather than a separate category."""
    h1, h2 = hex_color.lstrip("#"), toward.lstrip("#")
    a = [int(h1[i:i + 2], 16) for i in (0, 2, 4)]
    b = [int(h2[i:i + 2], 16) for i in (0, 2, 4)]
    return "#" + "".join(f"{round(x + (y - x) * amount):02x}" for x, y in zip(a, b))


def _dept_sort(dept: str) -> tuple[int, str]:
    return (_DEPT_ORDER.index(dept), "") if dept in _DEPT_ORDER else (len(_DEPT_ORDER), dept)


# ── Figures ───────────────────────────────────────────────────
def _icicle_fig(df: pd.DataFrame, team: str, level: str | None = None) -> go.Figure:
    """Department -> sub-unit -> person for one team.

    Person tiles are coloured by whether staff_moves.csv has them arriving at this
    team, so the blocks of new blood show up against the incumbent structure.

    `level` sets which node the treemap is zoomed to; see `_update_org_icicle` for
    why the callback needs to control it.
    """
    d = df[(df["team"] == team) & (df["name"] != "")].copy()
    fig = go.Figure()
    if d.empty:
        fig.update_layout(paper_bgcolor=CARD_BG, plot_bgcolor=CARD_BG, height=420,
                          font=dict(color=TEXT_MAIN),
                          annotations=[dict(text="No org data for this team",
                                            showarrow=False, font=dict(color=TEXT_DIM))])
        return fig

    d = d.sort_values(["department", "subunit", "seniority", "name"],
                      key=lambda s: s.map(_dept_sort) if s.name == "department" else s)

    # Branch nodes carry value 0 and branchvalues="remainder", so every branch is
    # exactly the sum of the people inside it and one person is always one unit of
    # area — no matter how deep they sit.
    ids, labels, parents, colors, values, hover = [], [], [], [], [], []
    edges: list[str] = []  # tile border = independently verified, see _VERIFY_CLR

    # A single root the departments hang off. In a treemap the root costs only the
    # thin pathbar strip (an icicle would spend a whole band on it), and without it
    # Plotly draws no pathbar at all -- which strands anyone who clicks into a tile.
    root = f"__{team}"
    ids.append(root); labels.append(team); parents.append("")
    colors.append(TEAM_COLORS.get(team, "#808080")); values.append(0)
    edges.append(CARD_BG)
    hover.append(f"<b>{team}</b><br>{len(d)} seats mapped<extra></extra>")

    depts = sorted(d["department"].unique(), key=_dept_sort)
    for i, dept in enumerate(depts):
        sub = d[d["department"] == dept]
        did = f"{dept}"
        n_new = int((sub["arrived_season"].notna()).sum())
        ids.append(did); labels.append(f"<b>{dept}</b>"); parents.append(root)
        colors.append(_DEPT_PALETTE[i % len(_DEPT_PALETTE)]); values.append(0)
        edges.append(CARD_BG)
        hover.append(f"<b>{dept}</b><br>{len(sub)} seats mapped"
                     f"<br>{n_new} filled by a tracked move<extra></extra>")

        for unit in sorted(sub["subunit"].unique()):
            grp = sub[sub["subunit"] == unit]
            parent_id = did
            if unit:
                uid = f"{did}|{unit}"
                ids.append(uid); labels.append(unit); parents.append(did)
                colors.append(_rgba_mix(_DEPT_PALETTE[i % len(_DEPT_PALETTE)]))
                edges.append(CARD_BG)
                values.append(0)
                hover.append(f"<b>{unit}</b><br>{dept}<br>{len(grp)} seats<extra></extra>")
                parent_id = uid
            for j, (_, p) in enumerate(grp.iterrows()):
                pid = f"{parent_id}|{p['name']}#{j}"
                ids.append(pid); labels.append(p["name"]); parents.append(parent_id)
                arrived = pd.notna(p["arrived_season"])
                colors.append(_ARRIVAL_CLR if arrived else _INCUMBENT_CLR)
                edges.append(_VERIFY_CLR if p["source_type"] != "community-doc" else CARD_BG)
                values.append(1)
                bits = [f"<b>{p['name']}</b>"]
                if p["role"]:
                    bits.append(p["role"])
                bits.append(f"<i>{dept}{' · ' + unit if unit else ''}</i>")
                if arrived:
                    bits.append(f"↳ joined from {p['arrived_from'] or 'n/a'} "
                                f"({int(p['arrived_season'])}, {p['arrived_status'].lower()})")
                if p["confidence"] == "uncertain":
                    bits.append("<i>source unsure of this entry</i>")
                if p["source_type"] != "community-doc":
                    bits.append(f"✓ {_VERIFY_LABEL.get(p['source_type'], p['source_type'])}")
                hover.append("<br>".join(bits) + "<extra></extra>")

    fig.add_trace(go.Treemap(
        ids=ids, labels=labels, parents=parents,
        values=values, branchvalues="remainder",
        marker=dict(colors=colors, line=dict(color=edges, width=1),
                    pad=dict(t=20, l=3, r=3, b=3)),
        tiling=dict(packing="squarify", pad=2),
        textfont=dict(size=10, color="#ffffff"),
        textposition="middle center",
        hovertemplate=hover, sort=False, maxdepth=4,
        level=level or root,
        pathbar=dict(visible=True, thickness=20, side="top",
                     textfont=dict(size=10)),
    ))
    fig.update_layout(
        paper_bgcolor=CARD_BG, plot_bgcolor=CARD_BG,
        font=dict(color=TEXT_MAIN, family="Inter, sans-serif", size=11),
        height=700, margin=dict(l=6, r=6, t=48, b=6),
        title=dict(text=f"{team} · {len(d)} seats mapped, by department",
                   font=dict(size=13)),
    )
    return fig


def _churn_fig(df: pd.DataFrame) -> go.Figure:
    """Share of each team's mapped seats in a department that a tracked move filled.

    A ratio within one biased sample, so the uneven coverage largely divides out —
    unlike the raw counts, which mostly measure LinkedIn visibility.
    """
    d = df[df["name"] != ""].copy()
    fig = go.Figure()
    if d.empty:
        fig.update_layout(paper_bgcolor=CARD_BG, plot_bgcolor=CARD_BG, height=380)
        return fig

    core = [x for x in ["Design", "Aerodynamics", "Vehicle Performance",
                        "Race Team", "Power Unit", "Operations",
                        "Executive", "C-Suite"] if x in set(d["department"])]
    teams = sorted(d["team"].unique())
    d["is_new"] = d["arrived_season"].notna()

    z, text, custom = [], [], []
    for dept in core:
        zrow, trow, crow = [], [], []
        for team in teams:
            cell = d[(d["team"] == team) & (d["department"] == dept)]
            n = len(cell)
            k = int(cell["is_new"].sum())
            pct = 100 * k / n if n else None
            # Below 4 mapped seats the share is too noisy to colour.
            zrow.append(pct if n >= 4 else None)
            trow.append(f"{k}/{n}" if n else "")
            crow.append([n, k])
        z.append(zrow); text.append(trow); custom.append(crow)

    fig.add_trace(go.Heatmap(
        z=z, x=teams, y=core, customdata=custom,
        colorscale=[[0, "#20242e"], [0.35, "#33506e"], [0.7, "#8a4a3c"], [1, ACCENT]],
        zmin=0, zmax=60, xgap=2, ygap=2,
        text=text, texttemplate="%{text}", textfont=dict(size=10, color="#e8e8e8"),
        hovertemplate=("<b>%{x} · %{y}</b><br>%{customdata[1]} of %{customdata[0]} "
                       "mapped seats filled by a tracked move<br>"
                       "%{z:.0f}%<extra></extra>"),
        colorbar=dict(title=dict(text="% of seats", font=dict(size=10)),
                      thickness=10, len=0.75, tickfont=dict(size=9)),
        hoverongaps=False,
    ))
    theme(fig, 420, "Where the churn landed · share of mapped seats filled by a tracked move")
    fig.update_xaxes(tickangle=-30, tickfont=dict(size=10), title_text=None)
    fig.update_yaxes(autorange="reversed", tickfont=dict(size=10), title_text=None)
    fig.update_layout(margin=dict(l=130, r=70, t=52, b=90))
    return fig


# ── Directory table ───────────────────────────────────────────
_TABLE_COLS = [
    {"name": "Team",       "id": "team"},
    {"name": "Department", "id": "department"},
    {"name": "Sub-unit",   "id": "subunit"},
    {"name": "Role",       "id": "role"},
    {"name": "Name",       "id": "name"},
    {"name": "Level",      "id": "band"},
    {"name": "Arrived",    "id": "arrived"},
    {"name": "Verified",   "id": "verified"},
]


def _directory_table(df: pd.DataFrame) -> dash_table.DataTable:
    d = df[df["name"] != ""].copy()
    d["band"] = d["seniority"].map(_SENIORITY_BANDS).fillna("Other / unspecified")
    d["arrived"] = [
        (f"{r.arrived_from or '—'} · {int(r.arrived_season)}"
         + (" (rumored)" if str(r.arrived_status).lower() == "rumored" else ""))
        if pd.notna(r.arrived_season) else ""
        for r in d.itertuples()
    ]
    d["verified"] = [
        "" if st == "community-doc" else _VERIFY_LABEL.get(st, st)
        for st in d["source_type"]
    ]
    d = d.sort_values(["team", "department", "seniority", "name"],
                      key=lambda s: s.map(_dept_sort) if s.name == "department" else s)

    style_cond = [{"if": {"row_index": "odd"}, "backgroundColor": "rgba(255,255,255,0.02)"}]
    for team in d["team"].unique():
        if team in TEAM_COLORS:
            style_cond.append({
                "if": {"filter_query": f'{{team}} = "{team}"', "column_id": "team"},
                "color": TEAM_COLORS[team], "fontWeight": "600"})
    style_cond.append({
        "if": {"filter_query": '{arrived} != ""', "column_id": "arrived"},
        "color": ACCENT})
    style_cond.append({
        "if": {"filter_query": '{verified} != ""', "column_id": "verified"},
        "color": "#f0f0f0", "fontWeight": "600"})

    return dash_table.DataTable(
        data=d[[c["id"] for c in _TABLE_COLS]].to_dict("records"),
        columns=_TABLE_COLS,
        filter_action="native", sort_action="native", page_size=25,
        style_as_list_view=True,
        style_table={"overflowX": "auto"},
        style_cell={"backgroundColor": CARD_BG, "color": TEXT_MAIN,
                    "border": f"1px solid {GRID_CLR}", "fontSize": "0.75rem",
                    "padding": "5px 8px", "textAlign": "left",
                    "fontFamily": "Inter, sans-serif",
                    "maxWidth": "260px", "textOverflow": "ellipsis",
                    "overflow": "hidden"},
        style_header={"backgroundColor": "#12121f", "color": TEXT_DIM,
                      "fontWeight": "600", "fontSize": "0.72rem",
                      "textTransform": "uppercase", "border": f"1px solid {GRID_CLR}"},
        style_filter={"backgroundColor": "#12121f", "color": TEXT_MAIN},
        style_data_conditional=style_cond,
    )


# ── Section ───────────────────────────────────────────────────
def org_section() -> html.Div:
    """Org-structure card rendered under the staff-moves board."""
    df = org_annotated()
    if df.empty:
        return html.Div(html.P(
            ["No org-structure data. Run ", html.Code("scripts/parse_org_structure.py"),
             " to build ", html.Code("data/org_structure.csv"), " from ",
             html.Code("data/org_structure_raw.txt"), "."],
            style={"color": TEXT_DIM, "fontSize": "0.8rem"}))

    named = df[df["name"] != ""]
    n_seats = len(named)
    n_teams = named["team"].nunique()
    n_tracked = int(named["arrived_season"].notna().sum())
    n_verified = int((named["source_type"] != "community-doc").sum())
    vacant = int((df["confidence"] == "vacant/unknown").sum())

    kpis = html.Div([
        kpi("SEATS MAPPED", f"{n_seats:,}",
            tooltip="Named individuals in the source document. NOT a headcount — "
                    "it covers 8-21% of each team's real staff."),
        kpi("TEAMS COVERED", str(n_teams),
            tooltip="Every current constructor, plus Mercedes HPP folded into Mercedes."),
        kpi("SEATS WE TRACK A MOVE FOR", f"{n_tracked:,}", color=ACCENT,
            tooltip="Mapped seats whose occupant appears in staff_moves.csv arriving "
                    "at that team."),
        kpi("SEATS INDEPENDENTLY VERIFIED", f"{n_verified:,}", color="#f0f0f0",
            tooltip="Seats checked against a team's own announcement, F1/FIA, or "
                    "press — not taken from the community document alone. "
                    "data/org_overrides.csv."),
        kpi("SEATS LISTED BUT UNFILLED", str(vacant), color="#FFB000",
            tooltip="Positions the source names but has no occupant for — a marker "
                    "of where a team is currently recruiting."),
    ], className="row g-2 mb-2", style={"display": "flex", "flexWrap": "wrap"})

    teams = sorted(named["team"].unique())
    default_team = "Mercedes" if "Mercedes" in teams else teams[0]

    chart_card = card(
        "Org Chart — who holds which seat",
        html.Div([
            html.Div([
                html.Span("Team", style={"color": TEXT_DIM, "fontSize": "0.72rem",
                                         "marginRight": "8px"}),
                dcc.Dropdown(
                    id="org-team", options=[{"label": t, "value": t} for t in teams],
                    value=default_team, clearable=False,
                    style={"width": "260px", "fontSize": "0.8rem"},
                    className="dash-dropdown-dark"),
                dbc.Button("Reset view", id="org-reset", size="sm",
                           color="secondary", outline=True, n_clicks=0,
                           style={"fontSize": "0.72rem", "marginLeft": "10px"}),
            ], style={"display": "flex", "alignItems": "center", "gap": "6px",
                      "marginBottom": "8px"}),
            dcc.Graph(id="org-icicle", figure=_icicle_fig(df, default_team), config=GFX),
            html.P([
                html.Span("■ ", style={"color": _ARRIVAL_CLR, "fontWeight": "700"}),
                "seat filled by someone on the staff-moves board   ",
                html.Span("■ ", style={"color": _INCUMBENT_CLR, "fontWeight": "700"}),
                "incumbent, no move on record.   ",
                html.Span("▢ ", style={"color": _VERIFY_CLR, "fontWeight": "700"}),
                "pale border = seat verified against a team announcement, F1/FIA or "
                "press. Click a department or sub-unit to zoom in, then Reset view "
                "to come back out.",
            ], style={"color": TEXT_DIM, "fontSize": "0.72rem", "marginTop": "4px",
                      "marginBottom": 0}),
        ]),
        info=("Data: data/org_structure.csv — department → sub-unit → person for "
              "one team, from the community document described below. Person "
              "tiles are red where staff_moves.csv records that person arriving at "
              "this team, so a recruitment drive shows up as a block of red inside "
              "one department. Hover any name for their role and, when we track "
              "it, where they came from and the season it first bites. Caveat: "
              "tile counts are seats the source could see, not headcount — it "
              "names 8-21% of a team's real staff and badly under-covers "
              "production, so do not read one team's chart as bigger than "
              "another's. The Team Size card above is the honest size comparison."),
    )

    churn_card = card(
        "Where the Churn Landed",
        html.Div([
            dcc.Graph(figure=_churn_fig(df), config=GFX),
            html.P("Read across a row to see which teams rebuilt that department; "
                   "down a column for one team's rebuild. Cells with fewer than 4 "
                   "mapped seats are left blank as too noisy to shade.",
                   style={"color": TEXT_DIM, "fontSize": "0.72rem",
                          "marginTop": "4px", "marginBottom": 0}),
        ]),
        info=("For each team × department: of the seats the source document maps, "
              "what share are held by someone staff_moves.csv records arriving at "
              "that team. Why a share and not a count: the document's coverage is "
              "uneven (7.8% of Alpine's real staff, 20.5% of Audi's), so raw "
              "counts largely measure how visible a team is on LinkedIn. Taking "
              "arrivals as a fraction of mapped seats keeps numerator and "
              "denominator inside the same biased sample, so most of that bias "
              "divides out. It is still not a hiring rate — both sides are capped "
              "by what the document and our move board happen to know, and a "
              "long-tenured department full of people who moved in 2024 reads the "
              "same as one hired last month. Cells under 4 mapped seats are "
              "suppressed."),
    )

    intro = html.P(
        ["The board above tracks people ", html.Em("moving"), ". This one maps "
         "where they sit once they land: department, sub-unit and named seat for "
         "every team on the grid. Joined together they answer the question the "
         "move list alone cannot — not just that a team signed six "
         "aerodynamicists, but ", html.Strong("which part of the aero group"),
         " those six now run."],
        style={"color": TEXT_DIM, "fontSize": "0.8rem", "marginBottom": "12px"})

    provenance = html.P(
        ["Source: a community-maintained org-structure document compiled from "
         "public LinkedIn profiles and posted to the f1technical ",
         html.Em("Moving F1-Staff"), " thread on 5 Aug 2026 — the same thread that "
         "feeds the move board above. It is one contributor's research, not an "
         "official team disclosure: roles carry his own uncertainty markers, "
         "some entries are stale (he reported Stephen Taylor's move to Aston "
         "Martin while his own chart still lists Taylor at Mercedes), and the "
         "coverage is uneven by team. Treated here as a strong lead, never as "
         "confirmation on its own."],
        style={"color": TEXT_DIM, "fontSize": "0.72rem", "marginTop": "10px",
               "marginBottom": "10px", "fontStyle": "italic"})

    body = html.Div([intro, kpis, chart_card, churn_card, provenance,
                     _directory_table(df)])
    return card(
        "Org Structure — the seat map behind the transfer market",
        body,
        info=("Data: data/org_structure.csv (1,300+ named seats across all 11 "
              "teams), parsed by scripts/parse_org_structure.py from a community "
              "document compiled from public LinkedIn profiles. Why: staff_moves "
              "tells you a team hired someone; this tells you what they hired them "
              "to run. The directory table at the bottom is fully "
              "searchable/sortable — filter by team, department, role or name, and "
              "the Arrived column shows where we track them coming from. IMPORTANT: "
              "seat counts are not headcounts. The document names between 7.8% "
              "(Alpine) and 20.5% (Audi) of each team's real staff and covers "
              "production at roughly a quarter of its true weight, because "
              "engineers keep public profiles and technicians largely do not."),
    )


@callback(Output("org-icicle", "figure"),
          [Input("org-team", "value"),
           Input("org-reset", "n_clicks"),
           Input("org-icicle", "clickData")],
          State("org-icicle", "figure"),
          prevent_initial_call=True)
def _update_org_icicle(team, _reset_clicks, click, fig):
    """Redraw the chart, and stop a click on a person from stranding the viewer.

    Plotly zooms into whatever tile you click. For a branch that is what you want;
    for a person it dives into a single tile with nothing inside it, and this
    Plotly build (6.8) draws no pathbar to climb back out of it — so a stray click
    on a name is a dead end. Person ids are the only ones carrying '#', so when
    one is clicked we redraw at that person's parent instead: the viewer stays
    exactly where they were and the click is simply inert.
    """
    trigger = ctx.triggered_id
    if trigger == "org-icicle":
        points = (click or {}).get("points") or []
        clicked = points[0].get("id", "") if points else ""
        if "#" not in clicked:
            return no_update  # a branch: let Plotly's own zoom do its job
        parent = clicked.rsplit("|", 1)[0]
        return _icicle_fig(org_annotated(), team, level=parent)
    return _icicle_fig(org_annotated(), team)
